;;;;;;;
; Theme Settings
;;;;;;;
[theme]
author = "Center for Public History + Digital Humanities"
title = "Curatescape Classic"
description = "Classic theme evolved from the first wave of Curatescape projects. Designed to accomodate a bold sitewide background image. Use of accompanying Curatescape plugin is strongly recommended."
license = "GPL"
website = "https://curatescape.org"
support_link = "https://forum.curatescape.org"
omeka_minimum_version="3.1.2"
omeka_tested_up_to="3.1.2"
version="4.0"
tags="Curatescape, map, tour"